public class CodeAnalyzer {

    public static void analyze(AstNode node) {

        if (node == null) {
            return;
        }

        // Ignore implicit declarations generated by Clang
        if (Boolean.TRUE.equals(node.isImplicit)) {
            return;
        }

        // Class
        if ("CXXRecordDecl".equals(node.kind)
                && node.name != null) {

            System.out.println("Class: " + node.name);
        }

        // Free function
        if ("FunctionDecl".equals(node.kind)
                && node.name != null) {

            System.out.println("Function: " + node.name);
        }

        // Class method
        if ("CXXMethodDecl".equals(node.kind)
                && node.name != null) {

            System.out.println("Method: " + node.name);
        }

        // Analyze children
        if (node.inner != null) {

            for (AstNode child : node.inner) {
                analyze(child);
            }
        }
    }
}